
const bttn = document.getElementById('bttn')
bttn.onclick = function() {
    var val = document.getElementById('findur').value;
    console.log(val);
    const names = ['Nike Air Max 95', 'Adidas xh123', 'Nike shox', 'adidas', 'nike', 'puma', 'Adidas', 'Nike', 'Puma', 'Adidas XR', 'Adidas Race', 'Adidas Niteball', 'Adidas Bounce', 'Adidas Superstar', 'Adidas Handball', 'Adidas Forum low(gold)', 'Adidas Responsabl', 'Adidas Streetball 2.0(white)', 'Adidas RACE+', 'Adidas Forget', 'Adidas LXcon', 'Adidas Streetball(gray)', 'Adidas Ozweego(white)', 'Adidas Jogger', 'Adidas Niteball(mix)', 'Adidas Forum mid', 'Adidas strutter', 'Adidas Dame 8', 'Adidas race', 'Adidas Strutter 2.0', 'Adidas Superstar(fonk)', 'Adidas Ozweego(black)', 'Adidas Slime', 'Adidas low', 'Adidas Forum Low(green)', 'Adidas Pipe', 'Adidas Streetball(vanilla)', 'Adidas mid',
'Nike Blazer', 'Nike Lebron 5', 'Nike Air Max 90', 'Nike Huarachi', 'Nike Vooper Max', 'Nike Sb', 'Nike Phase', 'Nike Air Monarch', 'Nike Air Force 1', 'Nike Air Max 97', 'Nike Blazer Mid 77', 'Nike Air Max 96', 'Nike Compt', 'Nike While', 'Nike Kyrie 7', 'Nike FB', 'Nike Blazer low', 'Nike S+', 'Nike Higle', 'Nike Swamp', 'Nike Blazer(blue)', 'Nike P2000', 'Nike Rout', 'Nike Court Vision', 'Nike Dunk Low', 'Nike Dunk High', 'Nike TN+',
'Puma cali', 'Puma Kiron Bonifiers', 'Puma sport remix', 'Puma suede classic+', 'Puma X-ray game', 'Puma rs X', 'Puma rider', 'Puma beast', 'Puma Gap++', 'Puma rs Y', 'Puma Cruis', 'Puma pulse', 'Puma rs MIX', 'Puma connect', 'Puma HR', 'Puma react2.0', 'Puma Find', 'Puma QT', 'Puma Unit', 'Puma RS3', 'Puma Fast', 'Puma RS3.1', 'Puma TY', 'Puma KP', 'Puma React 2.1', 'Puma Caspi', 'Puma RiderX', 'Puma Jiji', 'Puma Om'
  ];
     if(names.includes(val)){
    const find = new Map([
        ['Nike Air Max 95', 'page/пара 1.htm'],
        ['Adidas xh123', 'page/пара 2.htm'],
        ['Nike shox', 'page/пара 3.htm'],
        ['adidas', 'page/adidas.htm'],
        ['nike', 'page/nike.htm'],
        ['puma', 'page/puma.htm'],
        ['Adidas', 'page/adidas.htm'],
        ['Nike', 'page/nike.htm'],
        ['Puma', 'page/puma.htm'],
        ['Adidas XR', 'page/adik1.htm'],
        ['Adidas Race', 'page/adik2.htm'],
        ['Adidas Niteball', 'page/adik3.htm'],
        ['Adidas Bounce', 'page/adik4.htm'],
        ['Adidas Superstar', 'page/adik5.htm'],
        ['Adidas Handball', 'page/adik6.htm'],
        ['Adidas Forum low(gold)', 'page/adik7.htm'],
        ['Adidas Responsabl', 'page/adik8.htm'],
        ['Adidas Streetball 2.0(white)', 'page/adik9.htm'],
        ['Adidas RACE+', 'page/adik10.htm'],
        ['Adidas Forget', 'page/adik11.htm'],
        ['Adidas LXcon', 'page/adik12.htm'],
        ['Adidas Streetball(gray)', 'page/adik13.htm'],
        ['Adidas Ozweego(white)', 'page/adik14.htm'],
        ['Adidas Jogger', 'page/adik15.htm'],
        ['Adidas Niteball(mix)', 'page/adik16.htm'],
        ['Adidas Forum mid', 'page/adik17.htm'],
        ['Adidas strutter', 'page/adik18.htm'],
        ['Adidas Dame 8', 'page/adik19.htm'],
        ['Adidas Strutter 2.0', 'page/adik21.htm'],
        ['Adidas Superstar(fonk)', 'page/adik22.htm'],
        ['Adidas Ozweego(black)', 'page/adik23.htm'],
        ['Adidas Slime', 'page/adik24.htm'],
        ['Adidas low', 'page/adik25.htm'],
        ['Adidas Forum Low(green)', 'page/adik26.htm'],
        ['Adidas Pipe', 'page/adik27.htm'],
        ['Adidas Streetball(vanilla)', 'page/adik29.htm'],
        ['Adidas mid', 'page/adik30.htm'],
        ['Nike Blazer', 'page/nke1.htm'],
        ['Nike Lebron 5', 'page/nke2.htm'],
        ['Nike Air Max 90', 'page/nke3.htm'],
        ['Nike Huarachi', 'page/nke4.htm'],
        ['Nike Vooper Max', 'page/nke5.htm'],
        ['Nike Sb', 'page/nke6.htm'],
        ['Nike Phase', 'page/nke7.htm'],
        ['Nike Air Monarch', 'page/nke8.htm'],
        ['Nike Air Force 1', 'page/nke9.htm'],
        ['Nike Air Max 97', 'page/nke10.htm'],
        ['Nike Blazer Mid 77', 'page/nke13.htm'],
        ['Nike Air Max 96' , 'page/nke15.htm'],
        ['Nike Compt', 'page/nke16.htm'],
        ['Nike While', 'page/nke17.htm'],
        ['Nike Kyrie 7', 'page/nke18.htm'],
        ['Nike FB', 'page/nke19.htm'],
        ['Nike Blazer low', 'page/nke20.htm'],
        ['Nike S+', 'page/nke21.htm'],
        ['Nike Higle', 'page/nke22.htm'],
        ['Nike Swamp', 'page/nke23.htm'],
        ['Nike Blazer(blue)', 'page/nke24.htm'],
        ['Nike P2000', 'page/nke25.htm'],
        ['Nike Rout', 'page/nke26.htm'],
        ['Nike Court Vision', 'page/nke27.htm'],
        ['Nike Dunk Low', 'page/nke28.htm'],
        ['Nike Dunk High', 'page/nke29.htm'],
        ['Nike TN+', 'page/nke30.htm'],
        ['Puma cali', 'page/pima1.htm'],
        ['Puma Kiron Bonifiers', 'page/pima2.htm'],
        ['Puma sport remix', 'page/pima3.htm'],
        ['Puma suede classic+', 'page/pima4.htm'],
        ['Puma X-ray game', 'page/pima5.htm'],
        ['Puma rs X', 'page/pima6.htm'],
        ['Puma rider', 'page/pima7.htm'],
        ['Puma beast', 'page/pima8.htm'],
        ['Puma Gap++', 'page/pima9.htm'],
        ['Puma rs Y', 'page/pima10.htm'],
        ['Puma Cruis', 'page/pima12.htm'],
        ['Puma pulse', 'page/pima13.htm'],
        ['Puma rs MIX', 'page/pima14.htm'],
        ['Puma connect', 'page/pima15.htm'],
        ['Puma HR', 'page/pima16.htm'],
        ['Puma react2.0', 'page/pima17.htm'],
        ['Puma Find', 'page/pima18.htm'],
        ['Puma QT', 'page/pima19.htm'],
        ['Puma Unit', 'page/pima20.htm'],
        ['Puma RS3', 'page/pima21.htm'],
        ['Puma Fast', 'page/pima22.htm'],
        ['Puma RS3.1', 'page/pima23.htm'],
        ['Puma TY', 'page/pima24.htm'],
        ['Puma KP', 'page/pima25.htm'],
        ['Puma React 2.1', 'page/pima26.htm'],
        ['Puma Caspi', 'page/pima27.htm'],
        ['Puma RiderX', 'page/pima28.htm'],
        ['Puma Jiji', 'page/pima29.htm'],
        ['Puma Om', 'page/pima30.htm'],

        

      ]);
      const kros = find.get(val)
      window.open(kros)
     }
     else{
        window.open("page/Извините.htm")
   }
 };

